CREATE TABLE `staffTasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`ownerId` integer,
	`dueDate` text,
	`priority` text DEFAULT 'medium',
	`status` text DEFAULT 'pending' NOT NULL,
	`linkedJobId` integer,
	`linkedCustomerId` integer,
	`estimatedMinutes` integer,
	`blockedByTaskId` integer,
	`autoGenerated` integer DEFAULT false,
	`createdBy` integer,
	`createdAt` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
	`completedAt` text
);
