import * as db from "../db";
import { getXeroStatus } from "./xero";

const OPEN_STATUSES = ["pending", "in_progress"] as const;

/**
 * Creates a staff task only if no open (pending/in_progress) task already
 * carries this exact `ruleKey` — the dedup primitive every rule below uses,
 * so a sweep running every N minutes never spams a duplicate task for the
 * same underlying condition. A rule is free to fire again once its
 * previous task is completed/cancelled (a real regression, not noise).
 */
export async function ensureTask(
  ruleKey: string,
  data: {
    title: string;
    description?: string;
    priority?: "low" | "medium" | "high" | "urgent";
    linkedJobId?: number;
    linkedCustomerId?: number;
    linkedQuoteId?: number;
    linkedInvoiceId?: number;
  }
): Promise<boolean> {
  const existing = await db.getStaffTasks();
  const alreadyOpen = existing.some((t) => t.ruleKey === ruleKey && (OPEN_STATUSES as readonly string[]).includes(t.status));
  if (alreadyOpen) return false;

  await db.createStaffTask({
    ...data,
    autoGenerated: true,
    ruleKey,
  });
  return true;
}

/** Closes any open task for this ruleKey — used when a sweep finds the
 * condition that created a task no longer holds (e.g. the deposit got
 * paid), so the task list never lags behind reality. */
export async function resolveTask(ruleKey: string) {
  const existing = await db.getStaffTasks();
  const open = existing.filter((t) => t.ruleKey === ruleKey && (OPEN_STATUSES as readonly string[]).includes(t.status));
  for (const task of open) {
    await db.updateStaffTask(task.id, { status: "completed", completedAt: new Date().toISOString() });
  }
}

const DAY_MS = 86400000;

/** Deposit invoice sent but unpaid for more than 3 days → accounts follow-up. */
async function checkDepositInvoicesUnpaid() {
  const invoices = await db.getAllInvoices();
  const staleDeposits = invoices.filter(
    (inv) => inv.invoiceType === "deposit" && inv.status === "sent" && inv.sentAt && Date.now() - new Date(inv.sentAt).getTime() > 3 * DAY_MS
  );
  let created = 0;
  for (const inv of staleDeposits) {
    const ruleKey = `DEPOSIT_UNPAID:${inv.id}`;
    if (
      await ensureTask(ruleKey, {
        title: `Follow up unpaid deposit — ${inv.invoiceNumber}`,
        description: `Deposit invoice ${inv.invoiceNumber} ($${inv.totalDue.toFixed(2)}) was sent on ${new Date(inv.sentAt!).toLocaleDateString("en-AU")} and is still unpaid.`,
        priority: "high",
        linkedInvoiceId: inv.id,
        linkedCustomerId: inv.customerId,
      })
    ) {
      created++;
    }
  }
  // Resolve tasks for deposits that are no longer "sent" (paid, voided, etc).
  const resolvedInvoiceIds = invoices.filter((inv) => inv.invoiceType === "deposit" && inv.status !== "sent").map((inv) => inv.id);
  for (const id of resolvedInvoiceIds) await resolveTask(`DEPOSIT_UNPAID:${id}`);
  return created;
}

/** A job in an active (non-terminal) state with no technician assigned at
 * all → management assignment task. */
async function checkUnassignedJobs() {
  const jobs = await db.getJobs();
  const terminal = new Set(["closed", "cancelled"]);
  const active = jobs.filter((j) => !terminal.has(j.status));
  let created = 0;
  for (const job of active) {
    const assignments = await db.getJobAssignments(job.id);
    const ruleKey = `JOB_UNASSIGNED:${job.id}`;
    if (assignments.length === 0) {
      if (
        await ensureTask(ruleKey, {
          title: `Assign a technician — ${job.jobNumber}`,
          description: `Job ${job.jobNumber} has no technician assigned yet.`,
          priority: "high",
          linkedJobId: job.id,
          linkedCustomerId: job.customerId,
        })
      ) {
        created++;
      }
    } else {
      await resolveTask(ruleKey);
    }
  }
  return created;
}

/** A job marked completed/closed with no final invoice raised yet →
 * accounts task, so billing doesn't quietly fall through the cracks. */
async function checkJobsCompletedWithoutFinalInvoice() {
  const [jobs, invoices] = await Promise.all([db.getJobs(), db.getAllInvoices()]);
  const finishedStatuses = new Set(["completed", "final_invoice", "customer_collection", "closed"]);
  const finishedJobs = jobs.filter((j) => finishedStatuses.has(j.status));
  let created = 0;
  for (const job of finishedJobs) {
    const hasFinalInvoice = invoices.some((inv) => inv.jobId === job.id && inv.invoiceType === "final");
    const ruleKey = `JOB_NEEDS_FINAL_INVOICE:${job.id}`;
    if (!hasFinalInvoice) {
      if (
        await ensureTask(ruleKey, {
          title: `Raise final invoice — ${job.jobNumber}`,
          description: `Job ${job.jobNumber} is marked ${job.status} but has no final invoice yet.`,
          priority: "high",
          linkedJobId: job.id,
          linkedCustomerId: job.customerId,
        })
      ) {
        created++;
      }
    } else {
      await resolveTask(ruleKey);
    }
  }
  return created;
}

/** A material request approved but not actually ordered after 2 days →
 * purchasing reminder, distinct from the existing "approve this" task. */
async function checkMaterialRequestsNotOrdered() {
  const requests = await db.getMaterialRequests();
  const staleApproved = requests.filter(
    (r) => r.status === "approved" && r.approvedAt && Date.now() - new Date(r.approvedAt).getTime() > 2 * DAY_MS
  );
  let created = 0;
  for (const r of staleApproved) {
    const ruleKey = `MATERIAL_NOT_ORDERED:${r.id}`;
    if (
      await ensureTask(ruleKey, {
        title: `Order approved material — ${r.materialName}`,
        description: `${r.quantity}x ${r.materialName} was approved on ${new Date(r.approvedAt!).toLocaleDateString("en-AU")} but hasn't been marked ordered yet.`,
        priority: "medium",
        linkedJobId: r.jobId,
      })
    ) {
      created++;
    }
  }
  const resolvedRequestIds = requests.filter((r) => r.status !== "approved").map((r) => r.id);
  for (const id of resolvedRequestIds) await resolveTask(`MATERIAL_NOT_ORDERED:${id}`);
  return created;
}

/** One-time cleanup for tasks created by the old quote-level Xero sync
 * rule, now replaced by checkInvoicesNotSyncedToXero below — without this,
 * any task already open under the old ruleKey would linger forever, since
 * nothing still evaluates quotes for Xero sync status to resolve it. */
async function resolveStaleQuoteXeroSyncTasks() {
  const existing = await db.getStaffTasks();
  const stale = existing.filter(
    (t) => t.ruleKey?.startsWith("QUOTE_NOT_SYNCED_XERO:") && (OPEN_STATUSES as readonly string[]).includes(t.status)
  );
  for (const task of stale) {
    await db.updateStaffTask(task.id, { status: "completed", completedAt: new Date().toISOString() });
  }
  return stale.length;
}

/** An issued invoice that still isn't synced to Xero → accounts reminder.
 * Lives on the invoice, not the quote — a quote can still change, but an
 * issued invoice is the final document Xero should see. Only runs when
 * Xero is actually connected — with no connection, "not synced" is simply
 * true for every invoice and the reminder would be noise nobody can act on. */
async function checkInvoicesNotSyncedToXero() {
  await resolveStaleQuoteXeroSyncTasks();

  const xeroStatus = await getXeroStatus();
  if (!xeroStatus.connected) return 0;

  const invoices = await db.getAllInvoices();
  const issued = invoices.filter((i) => !["draft", "void", "refunded", "reversed"].includes(i.status));
  let created = 0;
  for (const invoice of issued) {
    const ruleKey = `INVOICE_NOT_SYNCED_XERO:${invoice.id}`;
    if (invoice.xeroSyncStatus === "not_synced" || invoice.xeroSyncStatus === "failed") {
      if (
        await ensureTask(ruleKey, {
          title: `Sync invoice to Xero — ${invoice.invoiceNumber}`,
          description: `Invoice ${invoice.invoiceNumber} is issued but ${
            invoice.xeroSyncStatus === "failed" ? "its last Xero sync failed" : "has never been synced to Xero"
          }.`,
          priority: "medium",
          linkedInvoiceId: invoice.id,
          linkedCustomerId: invoice.customerId,
        })
      ) {
        created++;
      }
    } else {
      await resolveTask(ruleKey);
    }
  }
  return created;
}

/**
 * Runs every automatic task rule in one pass. Safe to call repeatedly —
 * every rule is dedup'd by ruleKey and self-resolves once its underlying
 * condition clears, so this can run on a schedule without accumulating
 * stale or duplicate tasks.
 */
export async function runAllTaskRules() {
  const results = {
    depositsUnpaid: await checkDepositInvoicesUnpaid(),
    unassignedJobs: await checkUnassignedJobs(),
    jobsNeedingFinalInvoice: await checkJobsCompletedWithoutFinalInvoice(),
    materialsNotOrdered: await checkMaterialRequestsNotOrdered(),
    invoicesNotSyncedToXero: await checkInvoicesNotSyncedToXero(),
  };
  return { ...results, totalCreated: Object.values(results).reduce((sum, n) => sum + n, 0) };
}

// Exported for targeted testing without needing to wait for the full sweep.
export const _internal = {
  ensureTask,
  resolveTask,
  checkDepositInvoicesUnpaid,
  checkUnassignedJobs,
  checkJobsCompletedWithoutFinalInvoice,
  checkMaterialRequestsNotOrdered,
  checkInvoicesNotSyncedToXero,
};
